# Generated by Django 3.0.6 on 2020-05-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0004_media_dateuploaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
