# Generated by Django 3.0.6 on 2020-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0008_auto_20200601_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
